---
title: "Gotta Visualize 'Em All!"
subtitle: "INFO 526 - Summer 2026 - Final Project"
author: 
  - name: "Vincent Sciulli"
    affiliations:
      - name: "School of Information, University of Arizona"
description: "This project will jump into the world of Pokemon through the 'Pokemon' dataset provided by TidyTuesday to answer the questions of (1) which starter is the best, statistically, throughout the evolutionary stages? and (2) what does the type diversity look like through the various regions of Pokemon?"  
format:
   html:
    code-tools: true
    code-overflow: wrap
    embed-resources: true
editor: visual
execute:
  warning: false
  echo: false
---

## Introduction

This project will jump into the world of Pokemon through the 'Pokemon' dataset provided by TidyTuesday to answer the questions of (1) which starter is the best, statistically, throughout the evolutionary stages? and (2) what does the type diversity look like through the various regions of Pokemon? While the aforementioned questions will be answered, we'll also discover how well the Pokemon developers, GameFreak, balanced not just the partner Pokemon that accompanies us throughout our journeys, but also the available Pokemon that we'll meet through a given region.

## Approach

My approach going into this is to have my dataset pre-manipulated prior to getting into the plotting and analysis. This entailed getting data from bulbapedia to create my "starter", "evo_stage", and "region" variables and to remove duplicate or disqualified Pokemon like alternate forms (not changing types) and Mega-Evolutions (which are temporary boosts and not standalone Pokemon). Once this is achieved, I can begin question 1 where I'll have all the information needed. Then for question 2, some more manipulation will be needed to transform the dataset into one where the regions are listed alongside the types that appear in them.

## Analysis

I started off with preparing the dataset in a way that it would be friendly towards my two questions. Using data from bulbapedia.com, I added starter, evolution stage and region data to the dataset. Then after extracting the data, I created base_stat_total through mutate() and filtered out columns that were not to be included:

```{r}
#| label: Loading data and general data wrangling
#| include: false
#| warning: false

pacman::p_load(tidymodels, tidyverse, readxl, ggrepel)

pokemon <- read_excel("data/pokemon_df_filt.xlsx")

pokemon <- pokemon |>
  
  mutate(

    evo_stage = as.numeric(evo_stage),
    base_stat_total = (attack + defense + special_attack + special_defense + speed + hp)) |>
  
  select(-c("height", "weight", "species_id", "base_experience", "color_1", "color_2", "color_f", "egg_group_1", "egg_group_2", "url_icon", "url_image"))
```

Data wrangling was the most important step. Once I got the dataset looking the way it needed to be I was able to get going with the plotting and analysis. For the first question, I used methods from past assignments to create the facet plots for each evolution stage. Then plotted the starters in their respective stage and used aesthetics work to include color, shape and annotations.

The second question was trickier as more data wrangling needed to be done to capture my intent. I needed my data to go from a list of Pokemon, to a list of the regions with the types of Pokemon alongside to be totaled. So with some pivoting and grouping, this was accomplished:

```{#| Label: Final Project Q2 Data Wrangling}
#| include: false

pokemon_regions <- pokemon |>

  pivot_longer(
    cols = c(type_1, type_2),
    names_to = "primary/secondary",
    values_to = "type"
  )   |>
  filter(!type == "NA")|> 
  
  separate_rows(region, sep =",\\s*") |>
  
  group_by(region, type) |> 
    summarise(count = n(), .groups = "drop") |>
  
  mutate(
    region = str_trim(region),
    region = factor(region, levels = c("Kanto", "Johto", "Hoenn", "Sinnoh", "Unova", "Kalos", "Alola"))
  )
```

## Discussion

The two plots tell very interesting stories when it comes to how GameFreak balances Pokemon. With the first plot, one could draw from it that GameFreak has typically gone with a mirrored balancing approach. Where the starters that begin with the best stat total in their first stage, become the ones with the least stats in the final stage and vice versa. Generally, Grass falls in the former category and Fire in the latter with Water being in the middle. Looking at only final evolutions, Fire starters have a 4 out of 7 advantage for having the best stat_totals in their generation. With Swampert, Water, has the highest out of all generations. Grass generally has the lowest base stat totals going into final forms. GameFreak appears to have a bias towards their Fire starters.

The second plot gives us a overview of how diverse each region is in terms of its Pokemon population and the available choices a player would have in a play through. It is clear that Water appears the most frequent, with some cases being 56 more Pokemon than the lowest type in that region. There are types that hardly break 20 Pokemon in a given region with Dragon, Ghost, Steel and Ice being among these for most generations. This has more serious implications for game balance than the starters discussion as Water is seen as a strong type based off resistances and effectiveness. Having this many Pokemon of Water could be why Fire starters have higher stats in most generations and Grass has the fewest? Is this the way that GameFreak decides to balance?

## References

References were created using mybib.com and are in the MLA format. These references encompass the entire final project (presentation and writeup).

\[1\] KaihatsuYT. “Mt Coronet by KaihatsuYT on DeviantArt.” Deviantart.com, DeviantArt, 21 July 2019, www.deviantart.com/kaihatsuyt/art/Mt-Coronet-806533711. Accessed 2026.

\[2\] Bulbapedia. “Regional Pokédex - Bulbapedia, the Community-Driven Pokémon Encyclopedia.” Bulbapedia, bulbapedia.bulbagarden.net/wiki/Regional_Pok%C3%A9dex. Accessed 2026.

\[3\] “2021 Turtwig.” Inspiredpencil, 2021, ar.inspiredpencil.com/pictures-2023/turtwig. Accessed 2026.

\[4\] Sanderson, Steven P. “How to Create Tables in R (with Examples) – a Comprehensive Guide Using Base R, Dplyr, and Data.table – Steve’s Data Tips and Tricks.” Steve’s Data Tips and Tricks, 24 Feb. 2025, www.spsanderson.com/steveondata/posts/2025-02-24/. Accessed 2026.

\[5\] “Kable_styling Function - RDocumentation.” Www.rdocumentation.org, www.rdocumentation.org/packages/kableExtra/versions/1.4.0/topics/kable_styling. Accessed 2026.

\[6\] rfordatascience. “Tidytuesday/Data/2025/2025-04-01/Readme.md at Main · Rfordatascience/Tidytuesday.” GitHub, 2025, github.com/rfordatascience/tidytuesday/blob/main/data/2025/2025-04-01/readme.md. Accessed 2026.

\[7\] “Complete Themes — Ggtheme.” Ggplot2.Tidyverse.org, ggplot2.tidyverse.org/reference/ggtheme.html. Accessed 2026.

\[8\] “R: Separate a Collapsed Column into Multiple Rows.” R-Project.org, search.r-project.org/CRAN/refmans/tidytable/html/separate_rows.html. Accessed 2026.

\[9\] “Jitter Points to Avoid Overplotting — Position_jitter.” Ggplot2.Tidyverse.org, ggplot2.tidyverse.org/reference/position_jitter.html. Accessed 2026.

\[10\] Bulbapedia. “Help:Color Templates - Bulbapedia, the Community-Driven Pokémon Encyclopedia.” Bulbapedia, 17 Apr. 2026, bulbapedia.bulbagarden.net/wiki/Help:Color_templates. Accessed 2026.
